import cadquery as cq
import csv
import numpy as np
plateRadius = 15
plateCenterHole = 4
pinRadius = 3.5/2
pinInter = 18
SCALE= 150 # scale profile dimentions

# input data from csv file of wing profile 
data = np.genfromtxt('data/s7075-il.csv',delimiter=',')
pts = data[9:89]
# if we can normalize vectors< then we can scale it
def normalize(data: np.array) -> np.array:
    '''
    Input numpy 2D array, that describes wing profile
    Putput as list of vector Tuples
    cq.Sketch doent accepts any other format, even list of lists
    ''' 

    res = data/np.linalg.norm(data)
    res = res*SCALE
    res = [tuple(item) for item in res.tolist()]
    return res

pts2 = normalize(pts)

################
# Sketch zone
prof = (
        cq.Sketch()
        .spline(pts2)
        .close()
        .finalize()
        #.assemble()
        )
# Sketch Zone end


plate = (
        cq.Workplane()
        .circle(plateRadius)
        .circle(plateCenterHole)
        .rect(pinInter,pinInter,forConstruction=True)
        .vertices()
        .circle(pinRadius)
        .extrude(5)
        )

###########
#sweep test
path = (
        (10,-1,10),
        (50,15,-15),
        (100,0,0)
        )
pathWire = cq.Workplane().spline(path)
"""
res = (
        cq.Workplane('YZ')
        .placeSketch(prof)
        .sweep(pathWire)
        )
        """
###########
res2 = (
        cq.Workplane()
        .placeSketch(prof)
        )
def makeIt(workpl):
    for _ in range(10):
        workpl = (
                workpl
                .workplane(offset=10)
                .placeSketch(prof)
                .loft(combine=True)
                )
    return workpl
res2 = makeIt(res2)
debug (plate)
show_object(res2)
